package io.legaldocml.akn.element;

import io.legaldocml.io.XmlWriter;
import io.legaldocml.util.Buffers;

import java.io.IOException;

import static io.legaldocml.akn.AknElements.ACTIVE_MODIFICATIONS;

/**
 * The element activeModifications is a metadata container of the active modifications generated by the document.
 *
 * <pre>
 * 	 <xsd:element name="activeModifications" type="Amendments"/>
 * </pre>
 *
 * @author <a href="mailto:jacques.militello@gmail.com">Jacques Militello</a>
 */
public final class ActiveModifications extends Amendments {

    /**
     * Memory address.
     */
    private static final long ADDRESS_ACTIVE_MODIFICATIONS = Buffers.address(ACTIVE_MODIFICATIONS);

    /**
     * {@inheritDoc}
     */
    @Override
    public void write(XmlWriter writer) throws IOException {
        writer.writeStart(ADDRESS_ACTIVE_MODIFICATIONS, 19);
        super.write(writer);
        writer.writeEnd(ADDRESS_ACTIVE_MODIFICATIONS, 19);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String name() {
        return ACTIVE_MODIFICATIONS;
    }

}